config/routes.rb
Rails.application.routes.draw do
  root             "pages#home"
  get "about", to: "pages#about"

  devise_for :users, :controllers => { :registrations => "user/registrations" }
    match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  resources :users, only: [:index, :show]
  resources :friendships

  resources :posts do
    member do
      put "like", to: "posts#like"
      put "unlike", to: "posts#unlike"
    end
  end

  get 'my_friends', to: "users#my_friends"
  get 'search_friends', to: "users#search"
  post 'add_friend', to: "users#add_friend"
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => 'User'
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_votable

  belongs_to :user
  validates :user_id, presence: true
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, length: { maximum: 150 }

  def score
  self.get_upvotes.size - self.get_downvotes.size
  end

  def url_parse(link)
    URI.parse('link').host
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_voter

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :friendships
  has_many :friends, through: :friendships

  def not_friends_with?(friend_id)
    friendships.where(friend_id: friend_id).count < 1
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def self.search(param)
    return User.none if param.blank?

    param.strip!
    param.downcase!
    (name_matches(param) + email_matches(param)).uniq
  end

  def self.name_matches(param)
    matches('name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    where("lower(#{field_name}) like ?", "%#{param}%")
  end

  def increase_karma(count=1)
   update_attribute(:karma, karma + count)
  end

  def decrease_karma(count=1)
    update_attribute(:karma, karma - count)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(user)
    user_path(user)
  end

  def after_sign_out_path_for(user)
    posts_path
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def destroy
    @friendship = current_user.friendships.where(friend_id: params[:id]).first
    @friendship.destroy
    respond_to do |format|
      format.html { redirect_to :back }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :show, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @posts = Post.paginate(page: params[:page], per_page: 12)
  end

  def new
    @post = current_user.posts.build
  end

  def edit
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:success] = "Post was created successfully"
      redirect_to post_path(@post)
    else
      flash[:danger] = "Unable to process post"
      render 'new'
    end
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post was successfully updated"
      redirect_to post_path(@post)
    else
      flash[:danger] = "Unable to update post"
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @post.destroy
    flash[:danger] = "Post has been destroyed"
    redirect_to posts_path
  end

  def like
    @post = Post.find(params[:id])
    @post.liked_by current_user
    @post.user.increase_karma
    redirect_to :back
  end

  def unlike
    @post = Post.find(params[:id])
    @post.unliked_by current_user
    @post.user.decrease_karma
    redirect_to :back
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :description, :link)
    end

    def require_same_user
      if current_user != @post.user and !current_user.admin?
        flash[:danger] = "You can only edit or delete your own articles"
        redirect_to root_path
      end
    end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:name, :github, :twitter, :description)
    devise_parameter_sanitizer.for(:account_update).push(:name, :github, :twitter, :description)
  end

  def after_update_path_for(user)
    user_path(user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]

  def index
    @users = User.paginate(page: params[:page], per_page: 12)
  end

  def show
    @user = User.find(params[:id])
  end

  def my_friends
    @friendships = current_user.friends.paginate(page: params[:page], per_page: 12)
  end

  def search
    @users = User.search(params[:search_param])

    if @users
      @users = current_user.except_current_user(@users)
      render partial: "friends/lookup"
    else
      render status: :not_found, nothing: true
    end
  end

  def add_friend
    @friend = User.find(params[:friend])
    current_user.friendships.build(friend_id: @friend.id)

    if current_user.save
      redirect_to :back
    else
      redirect_to :back, flash[:error] = "There was an error with adding user as friend"
    end
  end

  def destroy
    @user = User.find(params[:id])

    if @user.destroy
       redirect_to users_path, notice: "User deleted."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <h2>#{sentence}</h2>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size=80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    image_tag(gravatar_url, alt: user.email)
  end
end

app/views/common/_spinner.html.erb
<div id="spinner" class="row col-md-12 text-center spinner" style="display: none;">
	<i class="fa fa-spinner fa-spin fa-2x"></i> Processing...
</div>

app/views/friends/_lookup.html.erb
<div class="container">
  <div id="friend-lookup">
    <%= form_tag search_friends_path, remote: true, method: :get, id: "friend-lookup-form" do %>
      <div class="form-group text-center col-md-12">
        <div class="col-md-2">
          <%= text_field_tag :search_param, params[:search_param],
                              placeholder: "name, email", autofocus: true,
                              class: 'form-control search-box input-sm' %>
        </div>
        <div class="col-md-2">
          <%= button_tag(type: :submit, class: "btn btn-sm btn-success") do %>
            <i class="fa fa-search"></i> Search
          <% end %>
        </div>
      </div>
    <% end %>
    <%= render 'common/spinner' %>
    <% if @users %>
    <% if @users.size > 0 %>
      <div id="friend-lookup-results" class="col-md-10">
        <div class="col-md-6">
          <%= render 'users/user', obj: @users %>
        </div>
      </div>
    <% else %>
      <p class="col-md-12">
        No people match this search
      </p>
    <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
<% flash.each do |name, msg| %>
  <div class='alert alert-<%="#{name}"%>'>
    <a href="#" class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
  <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="navbar-container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to "Share My Code", posts_path %>
      </div>
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "All users", users_path %></li>
          <li><%= link_to "All posts", posts_path %></li>
        </ul>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li><%= link_to gravatar_for(current_user, 25), user_path(current_user), id:"avatar-nav" %></li>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if current_user.admin? %>
              <li align="center"><strong>ADMIN</strong></li>
        <% end %>
            <li><%= link_to "New Post", new_post_path %></li>
            <li><%= link_to "My Profile", user_path(current_user) %></li>
            <li><%= link_to "My Friends", my_friends_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
        <li><%= link_to "Register", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodeChallenge</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>
<%= render 'layouts/messages' %>
<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<div class="container" id="about-page">
  <div class="col-xs-12">
  </div>
  <div class="col-md-2"></div>
  <div class="col-xs-3 col-md-1">
    <h3>Nate Lipp</h3>
    <h3>
      <i><%= link_to "", "http://www.github.com/nalipp", :target => "_blank", class:"fa fa-github-alt"%></i>
      <i><%= link_to "", "https://twitter.com/nateplipp", :target => "_blank", class:"fa fa-twitter-square"%></i>
    </h3>
  </div>
  <div class="col-xs-9 col-md-6">
    <h3>A place for developers to share and learn about code</h3>
    <p>
      When learning to code how can we do more than just follow and finish tutorails?<br/>
      What ways can we not just learn a concept but also build something original?<br/>
      How can we find other learners who are at a similar level?<br/>
    </p>
    <p>
      If you have any ideas about this topic.<br/>
      Or just want to chat. nateplipp@gmail.com<br/>
    </p>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
  <div class="col-xs-12">
    <h1>Share my Repo</h1>
    <h4>A place for aspiring developers to share and review code.</h4>
  </div>
  <div class="col-xs-12">
    <h3>Find</h3>
    <p>View code repositories from other users.</p>
  </div>
  <div class="col-xs-12">
    <h3>Share</h3>
    <p>Share your code creations.</p>
  </div>
  <div class="col-xs-12">
    <h3>Follow</h3>
    <p>Keep track of other who are at a similar level.</p>
  </div>
  <div class="col-xs-12">
    <% unless user_signed_in? %>
      <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm" %>
      <%= link_to "Log in", new_user_session_path, class: "btn btn-success btn-sm" %>
      <%#= link_to "Look around", posts_path, class: "btn btn-primary btn-sm" %>
    <% end %>
  </div>
</div>

<div class="container">
  <%= @feed_items %>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <div>
    <%= f.text_field :title, class: "form-control", placeholder: "Project title", autofocus: true %></br>
  </div>
  <div>
    <%= f.text_area :description, rows: 3, class: "form-control", placeholder: "Project description" %></br>
  </div>
  <div>
    <%= f.text_field :link, class: "form-control", placeholder: "Share your repository (link)" %></br>
  </div>
  <div>
    <%= f.submit class: "btn btn-primary btn-md" %>
    <h3>[ <%= link_to "Cancel", posts_path %> ]</h3>
  </div>
  <% end %>

app/views/posts/_post.html.erb
<% obj.each do |post| %>
<div class="row">
  <div class="col-md-1">
    <span id="no-space" class="h4"><%= link_to "", like_post_path(post), method: :put, class: "glyphicon glyphicon-menu-up" %>
    <div id="post-score"><%= post.score %></div>
    <span id="no-space" class="h4"><%= link_to "", unlike_post_path(post), method: :put, class: "glyphicon glyphicon-menu-down" %>
  </div>
  <div class="col-md-2">
    <div id="avatar"><%= link_to gravatar_for(post.user, 30), user_path(post.user) %></div>
    <h6><%= link_to post.user.name, user_path(post.user) if post.user.name? %></h6>
  </div>
  <div class="col-md-8 col-xs-12">
    <h5>
      <%= link_to post.title, post_path(post), id:"post-path"%>
      <%= link_to post.link, "http://#{post.link}", :target => "_blank", id:"post-link" %>
    </h5>
    <h5>
      <%= post.description %>
    </h5>
    <hr>
  </div>
    <div class="col-md-1">
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="post-container" align="center">
  <div class="col-xs-12">
    <div class="col-md-4 col-xs-1"></div>
      <div class="col-md-4 col-xs-10">
        <h3>Edit this project</h3>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="col-md-12">
    <div class="col-md-2"></div>
    <div class="col-md-8" id="pad-top">
      <h2 id="new-post-icon"><%= link_to " NewProject", new_post_path, class: "glyphicon glyphicon-plus"%></h2>
      <%= render 'posts/post', obj: @posts %>
      <div align="center">
	       <%= will_paginate @posts %>
	    </div>
    </div>
    <div class="col-md-2">
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="post-container" align="center">
  <div class="col-xs-12">
    <div class="col-md-4 col-xs-1"></div>
      <div class="col-md-4 col-xs-10">
        <h3>What have you been working on?</h3>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="col-md-12">
    <div>
      <div class="col-md-12">
        <h3>
          <%= @post.user.name %>
          <% if user_signed_in? %>
            <% if @post.user.id == current_user.id || current_user.admin? %>
              <%= link_to "", edit_post_path(@post), class: "glyphicon glyphicon-cog" %>
              <%= link_to "", post_path(@post), method: :delete, data: {confirm: "Are you sure"},
                                              class: "glyphicon glyphicon-trash" %>
        </h3>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="col-md-1">
      <h4><%= link_to gravatar_for(@post.user, 60), user_path(@post.user) %></h4>
      <h2><%= link_to "", posts_path, class: "glyphicon glyphicon-arrow-left" %></h2>
    </div>
    <div class="col-md-8">
    <strong><h4><%= @post.title %></strong> <span><%= link_to @post.link, "https://#{@post.link}",
                          :target => "_blank", id:"post-link" %></span></h4>
    <p><%= @post.description %></p>
    </div>
    <div class="col-md-3">
    </div>
  </div>
  <div class="col-md-12">
    <div class="col-md-8">

  </div>
  <div>

  </div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="pannel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this article from being saved
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div><br />
<% end %>

app/views/users/_friend.html.erb
<% if current_user.not_friends_with?(obj.id) %>
  <%= link_to "follow", add_friend_path(user: current_user, friend: obj),
                                    class: "btn btn-xs btn-success", method: :post %>
<% else %>
<span class="h3"><%= link_to "unfollow", friendship_path(obj), method: :delete,
                                  data: { confirm: "Are you sure?" },
                                  class:"btn btn-xs btn-danger" %></span>
<% end %>

app/views/users/_user.html.erb
<table>
  <tbody>
    <% obj.each do |user| %>
    <tr>
      <td id="user-table" class="col-xs-1"><%= link_to gravatar_for(user, 30), user_path(user) %></td>
      <% if user.github? %>
      <td><h4><i class="icon-space-left"><%= link_to "", "http://#{user.github}", :target => "_blank", class:"fa fa-github-alt", id:"icon-space"%></i></h4></td>
      <% else %>
        <td><h4></h4></td>
      <% end %>
      <% if user.twitter? %>
        <td><h4><i class="icon-space-left"><%= link_to "", "http://#{user.twitter}", :target => "_blank", class:"fa fa-twitter-square", id:"icon-space"%></i></h4></td>
      <% else %>
        <td><h4></h4></td>
      <% end %>
      <p><td id="user-table" class="col-xs-offset-1"><%= link_to "#{user.name}(#{user.posts.count})", user_path(user) %></td></p>
      <td>
        <% if user_signed_in? %>
          <%= render 'users/friend', obj: user %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/index.html.erb
<div class="container">
  <div class="col-md-12">
    <div class="col-md-3"></div>
    <div class=" col-md-6">
    <h1 class="col-md-offset-2">All users</h1>
    <%= render 'users/user', obj: @users %>
      <div class="col-md-offset-2">
        <%= will_paginate %>
      </div>
    <div class="col-md-3">
    </div>
  </div>
</div>

app/views/users/my_friends.html.erb
<div class="container">
  <div class="col-md-12">
      <%= render 'friends/lookup' %>
    <div class="col-md-6">
    <% if @friendships.size > 0 %>
      <h3>My Freinds</h3>
      <%= render 'users/user', obj: @friendships %>
      <div align="center">
        <%= will_paginate @friendships %>
      </div>
    <% else %>
      <div class="row col-xs-12">
        <p>You are not currently following anyone</p>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="col-md-12">
    <h1><%= @user.name %>
      <span>
      <% if user_signed_in? %>
        <% if @user.id == current_user.id %>
          <%= link_to "", edit_user_registration_path, class:"glyphicon glyphicon-cog" %>
        <% end %>
        <% if current_user.admin? %>
          <%= link_to "Destroy", admin_destroy_user_path, class:"btn btn-danger btn-xs", method: :delete, data: { confirm: "You sure?" } %>
        <% end %>
      <% end %>
      </span>
    </h1>
    <h4>Following(<%= @user.friendships.count %>)
      <% if @user.github? %>
        <i class="icon-space-left"><%= link_to "", "https://#{@user.github}", :target => "_blank", class:"fa fa-github-alt"%></i>
      <% end %>
      <% if @user.twitter? %>
        <i class="icon-space-left"><%= link_to "", "https://#{@user.twitter}", :target => "_blank", class:"fa fa-twitter-square"%></i>
      <% end %>
      <span class="icon-space-left h6"><%= @user.email %></span>
    </h4>
    <%= gravatar_for(@user, 100) %>
  </div>
  <div class="col-md-6">
    <h4>Karma(<%= @user.karma %>)</h4>
    <h4>About :</h4>
    <h5><%= @user.description %></h5>
    <% if user_signed_in? %>
      <%= render 'users/friend', obj: @user %>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="col-md-12">
    <div class="col-md-8" id="pad-top">
      <h4>User posts(<%= @user.posts.size %>) </h4>
    <%= render 'posts/post', obj: @user.posts %>
    </div>
    <div class="col-md-4">
    </div>
  </div>
</div>